### ISSUE TITLE
Error after 60 second wait for an item

### ISSUE THREAD

**Issue by 12As** [ArchiveTeam/terroroftinytown-client-grab#2]
If all shorteners are used, the following appears right before the item fails:

``````
Error communicating with tracker: 429 Client Error: xxx.xxx.xxx.xxx has pending claims in all shorteners. Check that your client is up to date, you're running at most 1 client per shortener then contact a tracker administrator to release any pending claims..

Trying again in 60 seconds.

                                                     <sixty seconds later>

Traceback (most recent call last):

  File "scraper.py", line 60, in <module>

    main()

  File "scraper.py", line 28, in main

    item_info = try_with_tracker(tracker_client.get_item)

  File "scraper.py", line 48, in try_with_tracker

    return func(*args, **kwargs)

  File "/data/data/projects/urlteam2-19d9e71/terroroftinytown/terroroftinytown/client/tracker.py", line 29, in wrapper

    six.reraise(TrackerError, str(error))

  File "<string>", line 2, in reraise

terroroftinytown.client.tracker.TrackerError: 429 Client Error: xxx.xxx.xxx.xxx has pending claims in all shorteners. Check that your client is up to date, you're running at most 1 client per shortener then contact a tracker administrator to release any pending claims.

Process RunScraper returned exit code 1 for Item 
Failed RunScraper for Item 
Waiting 10 seconds...```
``````

**Comment by sakgoyal** [comment]
is there an update on this? I would rather not have these in my logs if it's not a "real" error
